[package]
name = "smart2asm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
quick-xml = { version = "0.37.2", features = ["serialize", "serde-types"] }
glob = "0.3.2"
anyhow = "1.0.95"
heck = "0.5.0"
bytemuck = { version = "1.21.0", features = ["min_const_generics"] }
itertools = "0.14.0"